name: unet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - absl-py=2.1.0
  - anyio=4.7.0
  - brotli-python
  - brotlicffi
  - cffi
  - click
  - colorama  # optional on Linux, but harmless
  - contourpy
  - cycler
  - exceptiongroup
  - fastapi
  - fonttools
  - fsspec
  - grpcio
  - h11
  - jinja2
  - kiwisolver
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - numpy=2.2.5
  - openssl
  - packaging
  - pillow
  - protobuf
  - pycparser
  - pyparsing
  - pyqt
  - pyqt6-sip
  - pysocks
  - python-dateutil
  - qtbase
  - qtdeclarative
  - qtsvg
  - qttools
  - qtwebchannel
  - qtwebsockets
  - requests
  - scipy
  - setuptools
  - sip
  - six
  - sniffio
  - starlette
  - tk
  - tomli
  - tornado
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - uvicorn
  - werkzeug
  - wheel
  - xz
  - zlib
  - zstd

  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - charset-normalizer==3.4.2
      - filelock==3.13.1
      - huggingface-hub==0.34.3
      - idna==3.10
      - markdown==3.8
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyyaml==6.0.2
      - safetensors==0.5.3
      - segmentation-models-pytorch==0.5.0
      - simsimd==6.5.0
      - stringzilla==3.12.5
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.0
      - timm==1.0.19
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - typing-inspection==0.4.1
